### PR TITLE
Remaded

### PR DESCRIPTION
**Pull request by ra1nlox**
Hi, I just saw your project and wanted to improve it, as I have been looking for something like this for a long time. I really liked your work. I may have violated your license by adding my nickname to README.md, anyway, i'm sorry. I hope you like my improvements to your project. You can make an exe file for the Windows version if you want to. Anyway, I added this to README.md
[release.zip](https://github.com/ArkadSt/minecraft_instance_manager/files/5519688/release.zip)

### CODE REVIEW

**Comment by ArkadSt** [comment]
Hello, I really like the improvements you made. However, a number of changes needs to be made before I merge your pull request and make a release. Here is what i'm going to do:

1. unselect_instance doesn't need an argument. It should just unselect the currently selected instance. If nothing is selected then it should message "None of the instances are selected." 

2. Restore reset and duplicate functionality

3. "add to path.cmd" is better not to contain spaces in it's name .

About "add to path.cmd". Do I understand correctly that running this command ads minecraft-instance-manager.py to PATH so it's easily accessible on Windows? If so, some information about this should be added to README.

About the click package. Instructions on obtaining this package should be added to README. As an alternative option, it could be provided bundled (with all the appropriate references to their licence).

Did you use pyinstaller to make an exe? I'm not really sure that we need and exe version though. It would require maintenance, which means that I would have to install Windows. I will still consider this.

As soon as I finish, I will send you the modified version and you will comment on it .

P.S. You removed all the swearing(((

**Comment by ra1nlox** [comment]
Thanks for the answer.
I understand your recommendations and agree with them. Perhaps I should reconsider my policy regarding the orientation of software to a specific system, and make them multi-directional.
The special exe for Windows should be removed. As for adding information to the README, I am not good at English, adding this information would take me a long time to compose the text. Unselect-instance agree, my mistake, not thought. Personally, I don't see the point in restore, reset and duplicate functions, but I don't decide, and if you need it, it will be implemented. As I said, "add to path. cmd" should be removed to maintain neutrality among operating systems. We don't need Pyinstaller for the same reason.
If I do something wrong, forgive me, I am new to programming in creating such a program, before that I made simple programs and discord bots. Participating in your project is one of the achievements of my life.
In parallel with you, I will continue to work, and we will bring it to perfection. By the way, I would like to make a GUI for this program in PyQt5, but I'm not sure that I can, but I will do my best. Also, I would like to add a change of the Minecraft directory and Minecraft-Instances-Manager.
Thanks

**Comment by ArkadSt** [comment]
Could you please contact me via my public email so that I have yours? It would be easier to work together if I had your email.

**Comment by ArkadSt** [comment]
I have pushed all the changes. Could you please test it on Windows?

**Comment by ra1nlox** [comment]
I'm not at my computer right now, so I'll test it as soon as I can
My email: rainforcall@gmail.com

**Pull request merged**
